# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93bf9d8037c3d37e12888cd69ae83ef6d8687c4e15489ca08f29bc3108f71bd1649db71240922ea22aec7c3065beaaa0b75c8cdf8149e5ac7b0cf80f7e3744e7

test:
  secret_key_base: 88c55ca56ad8d3ceca36b6eb1923246f9c5b147fe0b614cb47dca25021af98b6b0020cfdd6dbc78a0668483e852a1f47c57e5e6539510fa14576bb2fcd9b5b52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
